export default [
    {
        id: 1,
        adTitle: 'Bus Shelter',
        district: 'Kathmandu',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img1.webp',
    },
    {
        id: 2,
        adTitle: 'Bus Shelter',
        district: 'Kaski',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img2.webp',
    },
    {
        id: 3,
        adTitle: 'Bus Shelter',
        district: 'Gorkha',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img3.webp',
    },
    {
        id: 4,
        adTitle: 'Traffic Island',
        district: 'Bhaktapur',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img4.webp',
    },
    {
        id: 5,
        adTitle: 'Traffic Island',
        district: 'Lalitpur',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img5.webp',
    },
    {
        id: 6,
        adTitle: 'Traffic Island',
        district: 'Banke',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img6.webp',
    },
    {
        id: 7,
        adTitle: 'LED Screen',
        district: 'Kathmandu',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img7.webp',
    },
    {
        id: 8,
        adTitle: 'LED Screen',
        district: 'Tanahu',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img8.webp',
    },
    {
        id: 9,
        adTitle: 'LED Screen',
        district: 'Butwal',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img9.webp',
    },
    {
        id: 10,
        adTitle: 'Digital Recycle Bin',
        district: 'Mustang',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img10.webp',
    },
    {
        id: 11,
        adTitle: 'Digital Recycle Bin',
        district: 'Kaski',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img11.webp',
    },
    {
        id: 12,
        adTitle: 'Digital Recycle Bin',
        district: 'Chitwan',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img12.webp',
    },
    {
        id: 13,
        adTitle: 'Street Clock',
        district: 'Kathmandu',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img13.webp',
    },
    {
        id: 14,
        adTitle: 'Street Clock',
        district: 'Gorkha',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img14.webp',
    },
    {
        id: 15,
        adTitle: 'Street Clock',
        district: 'Lalitpur',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img15.webp',
    },
    {
        id: 16,
        adTitle: 'Solar Street Light',
        district: 'Banepa',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img16.webp',
    },
    {
        id: 17,
        adTitle: 'Solar Street Light',
        district: 'Banke',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img17.webp',
    },
    {
        id: 18,
        adTitle: 'Solar Street Light',
        district: 'Bhaktapur',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img18.jpg',
    },
    {
        id: 19,
        adTitle: 'Billboard',
        district: 'Bhaktapur',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img19.webp',
    },
    {
        id: 20,
        adTitle: 'Billboard',
        district: 'Chitwan',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img20.jpg',
    },
    {
        id: 21,
        adTitle: 'Billboard',
        district: 'Lamjung',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img21.webp',
    },
    {
        id: 22,
        adTitle: 'Taxi Stand',
        district: 'Gorkha',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img22.webp',
    },
    {
        id: 23,
        adTitle: 'Taxi Stand',
        district: 'Sindhuli',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img23.webp',
    },
    {
        id: 24,
        adTitle: 'Taxi Stand',
        district: 'Dharan',
        city: 'Baneshwor',
        imageUrl: '/src/assets/images/service-images/img24.webp',
    },
]