export default [
    {
        id: 1,
        imageUrl: '/src/assets/images/blog-images/img1.webp',
        title: 'Bus Shelter',
        description: 'Bus shelters are engineered specifically for public use with a strong emphasis on safety, durability ease of maintenance and aesthetic appeal. Our Bus Shelters are equipped with significantly large display area (Light Box) for advertisement and public information. Our Bus Shelters are built up as per international standards with disable people friendly waiting area.',
        publishedData: '2023-07-24',
    },
    {
        id: 2,
        imageUrl: '/src/assets/images/blog-images/img2.webp',
        title: 'Traffic Island',
        description: 'Bus shelters are engineered specifically for public use with a strong emphasis on safety, durability ease of maintenance and aesthetic appeal. Our Bus Shelters are equipped with significantly large display area (Light Box) for advertisement and public information. Our Bus Shelters are built up as per international standards with disable people friendly waiting area.',
        publishedData: '2023-08-22',
    },
    {
        id: 3,
        imageUrl: '/src/assets/images/blog-images/img3.webp',
        title: 'LED Screen',
        description: 'Bus shelters are engineered specifically for public use with a strong emphasis on safety, durability ease of maintenance and aesthetic appeal. Our Bus Shelters are equipped with significantly large display area (Light Box) for advertisement and public information. Our Bus Shelters are built up as per international standards with disable people friendly waiting area.',
        publishedData: '2023-06-23',
    },
    {
        id: 4,
        imageUrl: '/src/assets/images/blog-images/img4.webp',
        title: 'Digital Recycle Bin',
        description: 'Bus shelters are engineered specifically for public use with a strong emphasis on safety, durability ease of maintenance and aesthetic appeal. Our Bus Shelters are equipped with significantly large display area (Light Box) for advertisement and public information. Our Bus Shelters are built up as per international standards with disable people friendly waiting area.',
        publishedData: '2023-08-20',
    },
    {
        id: 5,
        imageUrl: '/src/assets/images/blog-images/img5.webp',
        title: 'Street Clock(Mupi)',
        description: 'Bus shelters are engineered specifically for public use with a strong emphasis on safety, durability ease of maintenance and aesthetic appeal. Our Bus Shelters are equipped with significantly large display area (Light Box) for advertisement and public information. Our Bus Shelters are built up as per international standards with disable people friendly waiting area.',
        publishedData: '2023-08-25',
    },
    {
        id: 6,
        imageUrl: '/src/assets/images/blog-images/img6.webp',
        title: 'Solar Street Light',
        description: 'Bus shelters are engineered specifically for public use with a strong emphasis on safety, durability ease of maintenance and aesthetic appeal. Our Bus Shelters are equipped with significantly large display area (Light Box) for advertisement and public information. Our Bus Shelters are built up as per international standards with disable people friendly waiting area.',
        publishedData: '2023-07-10',
    },
    {
        id: 7,
        imageUrl: '/src/assets/images/blog-images/img7.webp',
        title: 'Bill Board',
        description: 'Bus shelters are engineered specifically for public use with a strong emphasis on safety, durability ease of maintenance and aesthetic appeal. Our Bus Shelters are equipped with significantly large display area (Light Box) for advertisement and public information. Our Bus Shelters are built up as per international standards with disable people friendly waiting area.',
        publishedData: '2023-05-02',
    },
    {
        id: 8,
        imageUrl: '/src/assets/images/blog-images/img8.webp',
        title: 'Taxi Stand',
        description: 'Bus shelters are engineered specifically for public use with a strong emphasis on safety, durability ease of maintenance and aesthetic appeal. Our Bus Shelters are equipped with significantly large display area (Light Box) for advertisement and public information. Our Bus Shelters are built up as per international standards with disable people friendly waiting area.',
        publishedData: '2023-08-30',
    },
]